[
    {
        "key": "dbln",
        "value": "%7B%22100081709692851%22%3A%22mc9tYujk%22%2C%2261572775084558%22%3A%22RHs7E4ae%22%7D",
        "domain": "facebook.com",
        "path": "/login/device-based/",
        "hostOnly": false,
        "creation": "2025-02-06T14:08:08.453Z",
        "lastAccessed": "2025-02-06T14:08:08.454Z"
    },
    {
        "key": "datr",
        "value": "EX6gZ2bEX9hupUaRQfCIp2a_",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-02-06T14:08:08.454Z",
        "lastAccessed": "2025-02-06T14:08:08.454Z"
    },
    {
        "key": "sb",
        "value": "EX6gZ_peskPSRaBJUlu7yXc4",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-02-06T14:08:08.454Z",
        "lastAccessed": "2025-02-06T14:08:08.454Z"
    },
    {
        "key": "dpr",
        "value": "2.1988937854766846",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-02-06T14:08:08.454Z",
        "lastAccessed": "2025-02-06T14:08:08.454Z"
    },
    {
        "key": "locale",
        "value": "en_US",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-02-06T14:08:08.454Z",
        "lastAccessed": "2025-02-06T14:08:08.454Z"
    },
    {
        "key": "vpd",
        "value": "v1%3B664x360x2",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-02-06T14:08:08.454Z",
        "lastAccessed": "2025-02-06T14:08:08.454Z"
    },
    {
        "key": "c_user",
        "value": "61572775084558",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-02-06T14:08:08.454Z",
        "lastAccessed": "2025-02-06T14:08:08.454Z"
    },
    {
        "key": "fr",
        "value": "0UlAjiXwXgr0rJ6c7.AWVGcdI8KVWKy2DbV4_GUpU64SqCfFMyP8qyNQ.BnoH4R..AAA.0.0.BnoPnQ.AWWOgqGF2ow",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-02-06T14:08:08.454Z",
        "lastAccessed": "2025-02-06T14:08:08.454Z"
    },
    {
        "key": "xs",
        "value": "6%3A502eETpMU5Q1IQ%3A2%3A1738602961%3A-1%3A-1",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-02-06T14:08:08.454Z",
        "lastAccessed": "2025-02-06T14:08:08.454Z"
    },
    {
        "key": "wd",
        "value": "360x664",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-02-06T14:08:08.454Z",
        "lastAccessed": "2025-02-06T14:08:08.454Z"
    },
    {
        "key": "wl_cbv",
        "value": "v2%3Bclient_version%3A2733%3Btimestamp%3A1738850795",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-02-06T14:08:08.454Z",
        "lastAccessed": "2025-02-06T14:08:08.454Z"
    },
    {
        "key": "fbl_st",
        "value": "101024484%3BT%3A28980846",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-02-06T14:08:08.454Z",
        "lastAccessed": "2025-02-06T14:08:08.454Z"
    }
]
